# Generated by Django 5.2.9 on 2026-01-04 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='Номер аудитории')),
                ('capacity', models.IntegerField(default=1, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кафедры')),
                ('room', models.CharField(max_length=50, verbose_name='Аудитория кафедры')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('code', models.CharField(max_length=50, verbose_name='Код дисциплины')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Семестр')),
                ('hours_lecture', models.IntegerField(default=0, verbose_name='Часы лекций')),
                ('hours_practice', models.IntegerField(default=0, verbose_name='Часы практики')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('prof', 'Профессор'), ('docent', 'Доцент'), ('senior', 'Старший преподаватель'), ('assistant', 'Ассистент'), ('other', 'Другое')], max_length=50, verbose_name='Должность')),
                ('rate', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.5)], verbose_name='Ставка')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.classroom', verbose_name='Рабочее место')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='AdditionalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('curator', 'Кураторство'), ('practice', 'Проведение практик'), ('publications', 'Контроль научных публикаций'), ('science', 'Научная работа'), ('methodical', 'Методическая работа'), ('other', 'Другое')], max_length=50, verbose_name='Вид работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('hours_per_month', models.IntegerField(default=0, verbose_name='Часов в месяц')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Дополнительная работа',
                'verbose_name_plural': 'Дополнительная работа',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.IntegerField(default=2, verbose_name='Часов в неделю')),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Ответственный преподаватель')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.employee', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Преподавание',
                'verbose_name_plural': 'Преподавание',
                'unique_together': {('employee', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='employees',
            field=models.ManyToManyField(through='department.Teaching', to='department.employee', verbose_name='Преподаватели'),
        ),
    ]
